In [1]:
import numpy as np
x = np.array([[1, 0, 0, 0], [1, 0, 1, 1], [0, 1, 0, 1]])
print("Input :- \n", x) 
print("Shape of input :- ", x.shape)

Input :- 
 [[1 0 0 0]
 [1 0 1 1]
 [0 1 0 1]]
Shape of input :-  (3, 4)


In [2]:
x = x.T
print("\nTranspose of input :- \n", x)


Transpose of input :- 
 [[1 1 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]]


In [3]:
y = np.array([[1], [1], [0]])
y

array([[1],
       [1],
       [0]])

In [4]:
y = y.T
print("\nTranspose of output :- \n", y)


Transpose of output :- 
 [[1 1 0]]


In [7]:
inputlayer_neurons = x.shape[0]  # number of features in data set
hiddenlayer_neurons = 4  # number of hidden layers neurons
output_neurons = 1  # number of neurons at output layer
weights_input_to_hidden = np.random.uniform(1, 2, size=(inputlayer_neurons, hiddenlayer_neurons))
weights_hidden_to_output = np.random.uniform( size=(hiddenlayer_neurons, output_neurons))
print("\nweights_input_to_hidden :- \n", weights_input_to_hidden)
print("\nweights_hidden_to_output :- \n", weights_hidden_to_output)




weights_input_to_hidden :- 
 [[1.29785205 1.31895382 1.18638042 1.92378874]
 [1.60616828 1.81522801 1.08903849 1.80174248]
 [1.16769091 1.99515112 1.10881723 1.11667437]
 [1.76268462 1.92685716 1.44064997 1.99809944]]

weights_hidden_to_output :- 
 [[0.65449827]
 [0.22016902]
 [0.71061061]
 [0.7214801 ]]


In [12]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

hiddenlayer_linear_transform = np.dot(weights_input_to_hidden.T, x)
hiddenlayer_activations = sigmoid(hiddenlayer_linear_transform)
print("\nhiddenlayer_activations :- \n", hiddenlayer_activations)



hiddenlayer_activations :- 
 [[0.78547326 0.98563126 0.9667168 ]
 [0.7890076  0.99473273 0.97684427]
 [0.76609308 0.97670276 0.92619706]
 [0.87256033 0.9935587  0.97811535]]


In [14]:
outputlayer_linear_transform = np.dot(weights_hidden_to_output.T, hiddenlayer_activations)
output = sigmoid(outputlayer_linear_transform)
print("Output :- \n", output)


Output :- 
 [[0.86549901 0.90678456 0.90129006]]


In [15]:
error = np.square(y - output)
print("\nError :- \n", error)


Error :- 
 [[0.01809052 0.00868912 0.81232378]]
